import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.3/+esm';

const URL='https://jkakvpsiiffnidggcqzc.supabase.co';
const KEY='sb_publishable_h_0XIxzs33psSZTyKPGr8w_aJoVLw92';
const supabase=createClient(URL,KEY);
const RANK={documented:6,strong:5,family_supplied:4,probable:3,hypothesis:2,unresolved:1};
const PALETTE=['#e7bea0','#b8d5de','#cbd6a6','#d2c2df'];
const FRONTIER_KEY='genealogyShowResearchFrontier';
const canvas=document.getElementById('treeCanvas');
const centre=document.getElementById('centreSelect');
const centreMe=document.getElementById('centreMe');
const state={people:[],rels:[],frontier:[],byId:new Map(),mode:'family',depthMode:'auto',loaded:false};

const nameOf=p=>[p?.given_names?.trim(),p?.surname?.trim()].filter(Boolean).join(' ')||'Unknown';
const firstName=p=>[(p?.given_names||'').trim().split(/\s+/)[0],p?.surname?.trim()].filter(Boolean).join(' ');
const yearText=p=>{const b=p?.birth_date?.slice(0,4)||'',d=p?.death_date?.slice(0,4)||'';return b&&d?`${b}-${d}`:b?`b. ${b}`:d?`d. ${d}`:''};
const person=id=>state.byId.get(id)||null;
const active=r=>r?.is_active!==false;

function parentEdges(id){return state.rels.filter(r=>active(r)&&r.relationship_type==='parent'&&r.person2_id===id).map(r=>({relationship:r,person:person(r.person1_id)})).filter(x=>x.person).sort((a,b)=>(RANK[b.relationship.source_status]||0)-(RANK[a.relationship.source_status]||0)||nameOf(a.person).localeCompare(nameOf(b.person)))}
function pair(id){const c=parentEdges(id),slots=[null,null],used=new Set();const f=c.findIndex(x=>x.person.gender==='male'),m=c.findIndex(x=>x.person.gender==='female');if(f>=0){slots[0]=c[f];used.add(f)}if(m>=0){slots[1]=c[m];used.add(m)}c.forEach((x,i)=>{if(!used.has(i)){const o=slots.findIndex(v=>v===null);if(o>=0)slots[o]=x}});return slots}
function partner(id){const edges=state.rels.filter(r=>active(r)&&['spouse','partner','former_spouse'].includes(r.relationship_type)&&(r.person1_id===id||r.person2_id===id)).map(r=>({r,p:person(r.person1_id===id?r.person2_id:r.person1_id)})).filter(x=>x.p);return edges.find(x=>x.r.relationship_status==='current'&&x.r.relationship_type!=='former_spouse')?.p||edges.find(x=>x.r.relationship_status==='ended_by_death'&&['spouse','partner'].includes(x.r.relationship_type))?.p||null}
function children(id){return state.rels.filter(r=>active(r)&&r.relationship_type==='parent'&&r.person1_id===id).map(r=>person(r.person2_id)).filter(Boolean).sort((a,b)=>(a.birth_date||'9999').localeCompare(b.birth_date||'9999'))}
function coupleChildren(a,b){if(!b)return children(a.id);const x=new Set(children(a.id).map(c=>c.id)),y=new Set(children(b.id).map(c=>c.id)),shared=[...x].filter(id=>y.has(id)).map(person).filter(Boolean);return (shared.length?shared:[...new Set([...x,...y])].map(person).filter(Boolean)).sort((p,q)=>(p.birth_date||'9999').localeCompare(q.birth_date||'9999'))}

function levelsFor(a,b,depth){const levels=[];let current=b?[...pair(a.id),...pair(b.id)]:pair(a.id);levels.push(current);for(let g=1;g<depth;g++){const next=[];current.forEach(e=>{if(!e?.person){next.push(null,null);return}next.push(...pair(e.person.id))});levels.push(next);current=next}return levels}
function depthMap(roots){const map=new Map();function walk(id,d,path){if(!id||path.has(id))return;map.set(id,Math.max(map.get(id)??-1,d));const n=new Set(path);n.add(id);parentEdges(id).forEach(x=>walk(x.person.id,d+1,n))}roots.forEach(id=>walk(id,0,new Set()));return map}
function autoDepth(a,b){const map=depthMap([a.id,b?.id].filter(Boolean));let max=Math.max(1,...map.values());state.frontier.filter(c=>c.is_active!==false).forEach(c=>{const d=map.get(c.anchor_person_id);if(d!==undefined)max=Math.max(max,d+1)});return max}
function frontierMap(a,b,levels,depth){const out=new Map();if(localStorage.getItem(FRONTIER_KEY)!=='1')return out;const pos=new Map(),add=(id,p)=>{if(!id)return;const l=pos.get(id)||[];l.push(p);pos.set(id,l)};add(a.id,{level:-1,base:0});if(b)add(b.id,{level:-1,base:2});levels.forEach((entries,l)=>entries.forEach((e,s)=>{if(e?.person)add(e.person.id,{level:l,slot:s})}));state.frontier.filter(c=>c.is_active!==false).forEach(c=>{const side=c.parent_slot==='mother'?1:0;(pos.get(c.anchor_person_id)||[]).forEach(p=>{const l=p.level+1;if(l<0||l>=depth)return;const s=p.level===-1?p.base+side:p.slot*2+side;if(levels[l]?.[s]?.person)return;const k=`${l}:${s}`,arr=out.get(k)||[];arr.push(c);out.set(k,arr)})});out.forEach(arr=>arr.sort((x,y)=>(x.priority??100)-(y.priority??100)));return out}

function polar(r,a){const t=(a-90)*Math.PI/180;return[600+r*Math.cos(t),600+r*Math.sin(t)]}
function sector(ri,ro,a,b){const p1=polar(ro,a),p2=polar(ro,b),p3=polar(ri,b),p4=polar(ri,a),large=b-a>180?1:0;return`M ${p1[0]} ${p1[1]} A ${ro} ${ro} 0 ${large} 1 ${p2[0]} ${p2[1]} L ${p3[0]} ${p3[1]} A ${ri} ${ri} 0 ${large} 0 ${p4[0]} ${p4[1]} Z`}
function rotation(a){return a>90&&a<270?a+180:a}
function evidence(path,status){if(status==='hypothesis'){path.setAttribute('fill-opacity','.42');path.setAttribute('stroke-dasharray','8 5')}else if(status==='probable'){path.setAttribute('fill-opacity','.62');path.setAttribute('stroke-dasharray','5 4')}else if(status==='family_supplied')path.setAttribute('fill-opacity','.82');else path.setAttribute('fill-opacity','.94')}
function branch(slot,level,family){const roots=family?4:2,per=(roots*2**level)/roots;return Math.min(roots-1,Math.floor(slot/per))}
function text(g,ns,value,y,cls,size){const n=document.createElementNS(ns,'text');n.setAttribute('x','0');n.setAttribute('y',String(y));n.setAttribute('class',cls);if(size)n.setAttribute('font-size',String(size));n.textContent=value;g.appendChild(n)}

function details(p){const n=document.getElementById('personName'),d=document.getElementById('personDetails');if(!p||!n||!d)return;n.textContent=nameOf(p);const rows=[];if(yearText(p))rows.push(['Life',yearText(p)]);if(p.birth_place)rows.push(['Birthplace',p.birth_place]);if(p.occupation_summary)rows.push(['Occupation',p.occupation_summary]);rows.push(['Source status',(p.source_status||'unresolved').replaceAll('_',' ')]);if(p.narrative_summary)rows.push(['Family note',p.narrative_summary]);d.innerHTML=rows.map(([a,b])=>`<div class="detail-line"><strong>${a}</strong>${b}</div>`).join('')}

function wedge(ns,entry,front,slot,level,ri,ro,a,b,family){const p=entry?.person||null,candidate=!p&&front?.length?front[0]:null,g=document.createElementNS(ns,'g'),path=document.createElementNS(ns,'path');g.dataset.fanLevel=String(level);g.dataset.fanSlot=String(slot);path.setAttribute('d',sector(ri,ro,a,b));path.setAttribute('stroke','#8c8175');path.setAttribute('stroke-width','1.05');if(p){path.setAttribute('fill',PALETTE[branch(slot,level,family)%4]);evidence(path,entry.relationship?.source_status||p.source_status);g.classList.add('person-node');g.dataset.personId=p.id;g.setAttribute('aria-label',nameOf(p));g.setAttribute('tabindex','0');g.addEventListener('click',()=>details(p))}else if(candidate){path.setAttribute('fill','#b8b8b8');path.setAttribute('fill-opacity','.72');path.setAttribute('stroke','#666');path.setAttribute('stroke-width','1.4');path.setAttribute('stroke-dasharray','4 3');g.classList.add('research-frontier-node');const title=document.createElementNS(ns,'title');title.textContent=[candidate.label,candidate.year_text,candidate.detail,candidate.evidence_note].filter(Boolean).join(' - ');g.appendChild(title)}else{path.setAttribute('fill','#e8e3dc');path.setAttribute('fill-opacity','.25');path.setAttribute('stroke-dasharray','5 4')}g.appendChild(path);const mid=(a+b)/2,[x,y]=polar((ri+ro)/2,mid),tg=document.createElementNS(ns,'g');tg.setAttribute('transform',`translate(${x} ${y}) rotate(${rotation(mid)})`);const count=(family?4:2)*2**level,size=count>=256?5.5:count>=128?6.2:count>=64?7.2:count>=32?8:count>=16?9:10.5;if(p){text(tg,ns,firstName(p),-2,'fan-label enhanced-fan-label',size);if(yearText(p))text(tg,ns,yearText(p),11,'fan-date enhanced-fan-date',Math.max(4.8,size-2))}else if(candidate&&count<=128){text(tg,ns,candidate.label||'Research lead',-3,'fan-label enhanced-fan-label frontier-fan-label',Math.max(5.6,size));text(tg,ns,[candidate.year_text,front.length>1?`+${front.length-1} alternate`:'FRONTIER'].filter(Boolean).join(' | '),10,'fan-date enhanced-fan-date frontier-fan-date',Math.max(4.8,size-1.5))}else if(!candidate&&count<=128)text(tg,ns,'?',-2,'fan-label enhanced-fan-label',size);g.appendChild(tg);return g}

function renderCentre(svg,ns,a,b){const disc=document.createElementNS(ns,'circle');disc.setAttribute('cx','600');disc.setAttribute('cy','600');disc.setAttribute('r','160');disc.setAttribute('class','family-centre-disc');svg.appendChild(disc);[a,b].filter(Boolean).forEach((p,i)=>{const x=b?(i?685:515):600,y=b?555:570,g=document.createElementNS(ns,'g'),r=document.createElementNS(ns,'rect'),t=document.createElementNS(ns,'text');g.classList.add('family-centre-person');g.dataset.personId=p.id;r.setAttribute('x',x-75);r.setAttribute('y',y-27);r.setAttribute('width','150');r.setAttribute('height','54');r.setAttribute('rx','14');r.setAttribute('class','family-centre-card');t.setAttribute('x',x);t.setAttribute('y',y+2);t.setAttribute('class','family-centre-name');t.textContent=firstName(p);g.append(r,t);g.addEventListener('click',()=>details(p));svg.appendChild(g)});if(b){const link=document.createElementNS(ns,'line');link.setAttribute('x1','590');link.setAttribute('y1','555');link.setAttribute('x2','610');link.setAttribute('y2','555');link.setAttribute('class','family-couple-link');svg.appendChild(link)}const kids=coupleChildren(a,b),width=Math.min(270,Math.max(170,kids.length*58));kids.forEach((c,i)=>{const x=kids.length===1?600:600-width/2+width*i/(kids.length-1),g=document.createElementNS(ns,'g'),circle=document.createElementNS(ns,'circle'),initial=document.createElementNS(ns,'text'),label=document.createElementNS(ns,'text');g.classList.add('family-child-node');g.dataset.personId=c.id;circle.setAttribute('cx',x);circle.setAttribute('cy','668');circle.setAttribute('r','23');circle.setAttribute('class','family-child-circle');initial.setAttribute('x',x);initial.setAttribute('y','672');initial.setAttribute('class','family-child-initial');initial.textContent=(c.given_names||'?')[0];label.setAttribute('x',x);label.setAttribute('y','708');label.setAttribute('class','family-child-label');label.textContent=firstName(c);g.append(circle,initial,label);g.addEventListener('click',()=>details(c));svg.appendChild(g)})}
function renderSingle(svg,ns,p){const g=document.createElementNS(ns,'g'),c=document.createElementNS(ns,'circle'),t=document.createElementNS(ns,'text');g.classList.add('person-node');g.dataset.personId=p.id;c.setAttribute('cx','600');c.setAttribute('cy','600');c.setAttribute('r','105');c.setAttribute('class','centre-card');t.setAttribute('x','600');t.setAttribute('y','600');t.setAttribute('class','centre-name');t.textContent=nameOf(p);g.append(c,t);g.addEventListener('click',()=>details(p));svg.appendChild(g)}

function installControls(){const oldMode=document.getElementById('treeViewMode'),oldDepth=document.getElementById('generationDepth');if(oldMode&&!oldMode.dataset.adaptive){const n=oldMode.cloneNode(true);n.dataset.adaptive='1';oldMode.replaceWith(n);n.addEventListener('change',()=>{state.mode=n.value;render()})}if(oldDepth&&!oldDepth.dataset.adaptive){const n=document.createElement('select');n.id='generationDepth';n.dataset.adaptive='1';oldDepth.replaceWith(n);n.addEventListener('change',()=>{state.depthMode=n.value;render()})}}
function refreshDepth(max){const s=document.getElementById('generationDepth');if(!s)return;s.replaceChildren();const a=document.createElement('option');a.value='auto';a.textContent=`Auto (${max})`;s.appendChild(a);for(let i=1;i<=max;i++){const o=document.createElement('option');o.value=String(i);o.textContent=String(i);s.appendChild(o)}if(state.depthMode!=='auto'&&Number(state.depthMode)>max)state.depthMode='auto';s.value=state.depthMode}

function render(){if(!state.loaded||!canvas||!centre?.value)return;installControls();const a=person(centre.value);if(!a)return;const b=state.mode==='family'?partner(a.id):null,family=Boolean(b&&state.mode==='family'),max=autoDepth(a,family?b:null);refreshDepth(max);const depth=state.depthMode==='auto'?max:Math.max(1,Math.min(max,Number(state.depthMode)||max)),levels=levelsFor(a,family?b:null,depth),fm=frontierMap(a,family?b:null,levels,depth),ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 1200 1200');svg.setAttribute('aria-label',family?`Family fan for ${nameOf(a)} and ${nameOf(b)}`:`Ancestor fan centred on ${nameOf(a)}`);const inner=family?180:125,gap=2,thick=(575-inner-gap*(depth-1))/depth;levels.forEach((entries,l)=>{const step=360/entries.length,ri=inner+l*(thick+gap),ro=ri+thick;entries.forEach((e,s)=>svg.appendChild(wedge(ns,e,fm.get(`${l}:${s}`)||[],s,l,ri,ro,s*step,(s+1)*step,family)))});family?renderCentre(svg,ns,a,b):renderSingle(svg,ns,a);canvas.replaceChildren(svg);const title=document.getElementById('viewTitle'),summary=document.getElementById('viewSummary'),status=document.getElementById('treeStatus');if(title)title.textContent=family?`${firstName(a)} & ${firstName(b)}`:nameOf(a);if(summary)summary.textContent=`Generation depth now follows the deepest recorded or active research-frontier ancestry (${max} generations). Choose Auto to keep this current as research grows.`;if(status)status.textContent=`${state.people.length} people loaded. Showing ${depth} of ${max} research-depth generations.`;details(a)}

async function load(){const [p,r,f]=await Promise.all([supabase.from('people').select('id,given_names,surname,gender,birth_date,death_date,birth_place,occupation_summary,narrative_summary,source_status,is_active'),supabase.from('relationships').select('*'),supabase.from('research_frontier_candidates').select('id,anchor_person_id,parent_slot,label,year_text,detail,evidence_note,priority,is_active').eq('is_active',true).order('priority')]);if(p.error||r.error)return;state.people=(p.data||[]).filter(x=>x.is_active!==false);state.rels=(r.data||[]).filter(active);state.frontier=f.error?[]:(f.data||[]);state.byId=new Map(state.people.map(x=>[x.id,x]));state.loaded=true;installControls();window.setTimeout(render,80)}

centre?.addEventListener('change',()=>window.setTimeout(render,10));centreMe?.addEventListener('click',()=>window.setTimeout(render,90));document.addEventListener('genealogy:research-frontier-changed',render);document.addEventListener('genealogy:tree-suggestions-updated',async()=>{await load();render()});supabase.auth.onAuthStateChange((_e,s)=>{if(s)load()});const{data:{session}}=await supabase.auth.getSession();if(session)await load();
